name: Issues
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  IssueDetails:
    runs-on: ubuntu-latest
    steps:
      - name: Event Name
        run: echo "${{ github.event_name }}"
      - name: Event Details
        run: echo "${{ toJSON(github.event) }}"
